### PR TITLE
fix windows file access handling

### LINKED ISSUE #140: Error while proxying request: getting credentials: exec: executable gscloud.exe failed with exit code 1
I'm running into an issue with file access when trying to use the gscould util after my system has been in hibernation mode for some time (usually 1-2 days).

kubectl version: 1.22.5
gscloud version: 0.11.0 (Git commit: 4ccd023bafe07d9849c71fa850264d79e7a14488)
go version: go1.16.12
OS: Windows 11 Build 22000.556

When trying to use kubectl with `kubectl get namespaces` I get the following error message:
```
Could not load cached kubeconfig: remove C:\Users\USERNAME\AppData\Local\gscloud\exec-credential\41e65f36-059d-4a14-93c8-c2fb29e490fc.json: The process cannot access the file because it is being used by another process.
```

Using the same version of the gscloud in the WSL2 and the utility works fine.

As a workaround I can delete the file and then reconnect using `kubectl get namespaces` and everything works as expected. Using the process explorer I couldn't find a process accessing the file.

### PR DESCRIPTION
**Pull request by nhanus**
On Windows, you cannot delete a file that is in use. With defer, the file is only closed after the function is executed. The fix ensures that the file is closed before deletion and otherwise closes the file with defer after the function, without throwing an error, when it is closed.
fixed #140 too

### CODE REVIEW

File: cmd/kubernetes.go [hunk 1]
```diff
@@ -347,7 +347,9 @@ func loadCachedKubeConfig(id string) (*clientauth.ExecCredential, error) {
 		return nil, err
 	}
 
-	defer f.Close()
+	defer func() {
```
Comment (nvthongswansea) [inline cmd/kubernetes.go]: imho, I think we don't need to alter this line.

**Comment by nvthongswansea** [comment]
@nhanus Thank you for your contribution.

File: cmd/kubernetes.go (hunk 1 above)
Comment (nhanus) [reply cmd/kubernetes.go]: I didn't know exactly how defer handles errors, so I caught a possible error when the file was already closed. But after delving deeper into defer, you're absolutely right, and I don't need to alter this line.

**Comment by nvthongswansea** [comment]
LGTM. Thank you!
